### ISSUE TITLE
Include PDF in repo perhaps

### ISSUE THREAD

**Issue by kach** [colah/Motivated-Topology#2]
I loved this book. Topology axioms feel a lot more intuitive now.

It would be nice not to have to compile it to read it, though, especially if I wanted to share a link to a non-TeX-savvy friend (or someone who is using a smartphone). Lately, Github's web interface displays PDF files that are included in the repository. Though it messes with diffs and version control a tiny bit, it's a nice way to distribute it. Alternatively, you could host a PDF on-line on your website, or elsewhere and put a link in the README. :-)

(P.S. Pedantic: `s/bellow/below/` on page 15 with the graph diagrams.)

**Comment by colah** [comment]
PDF is in the repo, just on a different branch to keep things cleaner:

https://github.com/colah/Motivated-Topology/raw/pdf-release/topology.pdf

I'll add a comment to the README to clarify this.
